name: Generate doc test

on:
  push:
#    paths:
#      - 'README.md'
   
jobs:
  convert:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: voronizer/md-to-pdf-action@1
        with:
          input-file: 'README.md'
          output-file: 'README.pdf'
      - uses: actions/upload-artifact@v3
        with:
          name: README.pdf
          path: README.pdf